name: Download and prepare MAD-X sources
inputs:
  madx_version:
    default: '5.06.00'
    description: 'MAD-X version to checkout and fetch'

runs:
  using: composite
  steps:
    - name: Checkout MAD-X source
      shell: bash
    - run: |
        mkdir src
        git clone git://github.com/MethodicalAcceleratorDesign/MAD-X \
          /src/MAD-X -b ${{ inputs.madx_version }} --depth 1
