name: Download and prepare MAD-X sources
inputs:
  madx_version:
    default: '5.06.00'
    description: 'MAD-X version to checkout and fetch'

runs:
  using: composite
  steps:
    - name: Download MAD-X source
      shell: bash
      run: |
        REPO=https://github.com/MethodicalAcceleratorDesign/MAD-X
        wget "$REPO/archive/${{ inputs.madx_version }}.tar.gz"

    - name: Extract MAD-X source
      shell: bash
      run: |
        tar -xzf "${{ inputs.madx_version }}.tar.gz" \
          --one-top-level=src/MAD-X \
          --strip-components 1
