name: Download and prepare MAD-X sources
inputs:
  madx_version:
    default: '5.06.00'
    description: 'MAD-X version to checkout and fetch'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        repository: MethodicalAcceleratorDesign/MAD-X
        ref: ${{ inputs.madx_version }}
        path: src/MAD-X
