name: Build shared library
on:
  push:
  pull_request:

jobs:
  linux32:
    name: Linux (32, i686)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/checkout-madx
      - name: Build
        uses: docker://quay.io/pypa/manylinux1_i686
        with:
          args: ./build_on_linux.sh
      - name: Check linked libraries
        run: ldd dist/lib/madx.so
      - uses: actions/upload-artifact@v2
        with:
          name: linux32
          path: dist

  linux64:
    name: Linux (64, x86_64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/checkout-madx
      - name: Build
        uses: docker://quay.io/pypa/manylinux1_x86_64
        with:
          args: ./build_on_linux.sh
      - name: Check linked libraries
        run: ldd dist/lib/madx.so
      - uses: actions/upload-artifact@v2
        with:
          name: linux64
          path: dist

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - bits: 32
            arch: i686
          - bits: 64
            arch: x86_64
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW${{ matrix.bits }}
          install: >
            base-devel
            mingw-w64-${{ matrix.arch }}-toolchain
            mingw-w64-${{ matrix.arch }}-cmake

      - uses: ./.github/checkout-madx
      - run: ./build_on_msys2.sh

      - name: Check linked libraries
        run: ldd dist/bin/madx.dll

      - uses: actions/upload-artifact@v2
        with:
          name: win${{ matrix.bits }}
          path: dist
